### ISSUE TITLE
Access of `originalUrl` not possible anymore

### ISSUE THREAD

**Issue by delijah** [kapouer/express-urlrewrite#8]
We use the originalUrl variable extensively in our stack, but recently the logic behind it got changed (https://github.com/kapouer/express-urlrewrite/pull/1). Now we cannot upgrade to the newest version anymore. Could you help us how to get around this?

**Comment by kapouer** [comment]
I think the issue with #1 and https://github.com/angular/universal/blob/1adb89372704be7761e5c2ac8efeda918342ac0b/modules/express-engine/src/main.ts#L51 is that they use `req.originalUrl` instead of properly using `req.baseUrl + req.url`.

request | url | originalUrl | baseUrl | path
-- | -- | -- | -- | --
/login?pwd=123 | /login?pwd=123 | /login?pwd=123 |   | /login
/admin/login?pwd=123 | /login?pwd=123 | /admin/login?pwd=123 | /admin | /login

Let's see what they think about that.

**Comment by delijah** [comment]
Hmmm, i understand. But this library was not written for the use with angular only, isn't it? Not sure if we should change core functionality in order to make it work with a specific software 🤔

**Comment by kapouer** [comment]
Yes, indeed, it was not meant to be used by angular prerendering at all.
It's just that i got sloppy at some point and accepted PR #1 without really understanding what it was about.
I think i'll revert that change, and let them deal with https://github.com/angular/universal/issues/2564

**Comment by kapouer** [comment]
For the record, i'm doing prerendering too in an express framework, and i'm sure they can avoid the issue by doing what i suggest.

**Comment by kapouer** [comment]
angular/universal has fixed their side, so i just released express-urlrewrite@2.0.0.
